[platformio]
default_envs = inkpulse_e1001

[env:inkpulse_e1001]
platform = platformio/espressif32@6.12.0
board = seeed_xiao_esp32s3
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson@7.4.2
    bitbank2/PNGdec@1.1.6
    https://github.com/Seeed-Studio/Seeed_GFX.git#V3.1.0
build_flags =
    -D BOARD_HAS_PSRAM
    -D PNG_MAX_BUFFERED_PIXELS=800
    -D INKPULSE_FIRMWARE_VERSION=\"0.1.0\"
    -I include

